### ISSUE TITLE
Sharpness Modifiers

### ISSUE THREAD

**Issue by ShatteredSpark** [mrmin123/the-calculating-palico#4]
Not sure if this is the right place to leave this, sorry if it isn't. The sharpness modifiers for Green, Blue, and Purple are 1.05, 1.20, and 1.45 respectively. Don't know where the wrong numbers came from originally, but Kiranico updated it a while back.

**Comment by mrmin123** [comment]
I'm not actively maintaining this project anymore but this was a small enough change so I updated it. Thanks!
