### ISSUE TITLE
Modifiers aren't taken into account when calculating Charge Phial damage

### ISSUE THREAD

**Issue by Aureliaar** [mrmin123/the-calculating-palico#5]
As per title.

**Comment by mrmin123** [comment]
@Aureliaar Could you expand on the issue a bit? I haven't touched MH4U or the Calculating Palico in almost half a year so my memory's a bit rusty for both game mechanics and the codebase.

**Comment by Aureliaar** [comment]
The Elemental charge blades have certain attacks that consume a Phial to do a certain amount of damage, which causes a 'burst'.
In the specific, the Axe: Super Amped Element Discharge with 5 phials has an absurdly high elemental damage coefficient (13.5x per phial, which nets out as 67.5x), which is calculated properly and nets out, on my test setup (Dear Hecatelia against a HR Fatalis), ~250 damage at 1 phial and 153 damage per successive phial, which is perfectly coherent with it all.
However, activating Fire atk+3, which increases roughly all fire damage by 40% (Moving fire attack from 360 to 504, / which is exactly +40%), doesn't increase phial damage at all, while working on the direct hit. Elemental damage for every phial remains at 153.

**Comment by Aureliaar** [comment]
I can edit it myself if you give me a pointer or two .- I've found the interested option in cbladePhials \ cbPhialOptions, but i can't then find where the value is consumed.

**Comment by mrmin123** [comment]
@Aureliaar I don't think I'll have time to work on this tonight but here's what I gathered from looking at the code real fast.

I believe the relevant calculations are done in the `cb_Exp` and `cb_ExpEq` functions in the main `calculatingPalico` module in `include.js`. Looking at those functions, the `modmul` value is passed in but defaults to 0 all the time.

`cb_Exp is called on line 183 and 214 in `include.js`:

```
if (weaponType.id == 10 && weapon.phial == 'Impact') {
    raw.push(cb_Exp(motion.name, weapon.attack, weaponType.modifier, 0, 100, modifiers.phialc, weapon.phial));
}
```

```
// charge blade elemental phial damage
if (weaponType.id == 10 && weapon.phial == 'Element' && weapon.elements[0].id != 0) {
    rawE[elementIndex] += cb_Exp(motion.name, weapon.elements[0].attack, 10, 0,
        damage[3 + elementType], modifiers.phialc, weapon.phial);
}
```

The first is for Impact phial calculations, so maybe should stay unchanged (unless there are Armor Skills which should effect the charge blade explosions). The second is for Elemental phials, so maybe try replacing the 0 with whatever value stores the elemental modifier value, and then modifying `cb_Exp`'s `cb_ExpEq` calls to include the passed `modmul` value. Another consideration that I can't remember off the top of my head right now how I resolved previously is making sure that the correct elemental multiplier is applied (only Fire modifier on Fire weapons, Water modifier on Water weapons, etc)

Hope this helps. If you don't get to fixing it I'll revisit it again sometime next week and try to implement it then.

**Comment by Aureliaar** [comment]
There's technically Artillery Novice\God (1.2x, 1.3x, 1.4x) for Impact Phials, but those aren't even selectable as skills.
I don't have a JS setup right now, so i can't test the changes, but it should be:
+ Add parameter modadd to cb_exp and cb_expEq calls
+ In cb_expEq calls, pass modmul instead of 0, and add modadd as parameter
+ in the cb_expEq damage calculation, take modadd into consideration:
	`return Math.floor(Math.floor( ((attack/ modifier)+(modadd / 10)) * (1 + modmul) * (res / 100)) * phialMulti) * expCount * phialCount; `
+ in the call, swap  the 0 for modmul, and add a parameter for modadd.

**Comment by Aureliaar** [comment]
Actually, it seems that you had actually corrected the value before passing it: (rr 209)
`					rawE[elementIndex] += eDmg(epwrs[elementIndex], damage[3 + elementType],
							modifiers.elem[elementType].eMul, modifiers.elem[elementType].eAdd, emod);`
This line should probably be moved after the call to cbexp. I'm not sure what it actually does, honestly - it seems to be adding the true damage to the raw?

Also, to get the proper modifier, it seems you've already built it up properly, and it's as easy as calling:
`modifiers.elem[elementType].eMul, modifiers.elem[elementType].eAdd`

**Comment by mrmin123** [comment]
@Aureliaar The line at 209 is for calculating the elemental damage of the base weapon, sans phial explosions. Line 213 adds the additional elemental damage done by the phial explosions to this value.

I pushed a branch with the proposed changes here: [5_charge_phial](https://github.com/mrmin123/the-calculating-palico/tree/5_charge_phial). If you can download and test locally (just open `index.html` in your browser... no installation necessary as long as you have all the files), I'd appreciate it.

**Comment by mrmin123** [comment]
Merging and hoping that it's correct!

**Comment by Aureliaar** [comment]
Sorry, i thought had answered - the branch works perfectly, and so does the now online pushed version.
Thank you for your work.

**Comment by mrmin123** [comment]
Awesome, thanks for the confirmation.
